### ISSUE TITLE
Implement Discord GameSDK support

### ISSUE THREAD

**Issue by Xottab-DUTY** [arjunattam/vscode-chat#266]
Documentation: https://discord.com/developers/docs/game-sdk/sdk-starter-guide 😉

<details>
<summary>Original text</summary>
I don't see that it's in Beta now. Documentation is available and it's not closed: https://discordapp.com/developers/docs/reference

So, it's time to implement RPC support! 😉
</details>

**Comment by arjun27** [comment]
Hey @Xottab-DUTY! Thanks for your interest for Discord RPC. I'm eager to set it up as well.

The link to Discord RPC is actually: https://discordapp.com/developers/docs/topics/rpc - and it is still in private beta as of now.

**Comment by Xottab-DUTY** [comment]
Oh =(
Sorry

**Comment by Xottab-DUTY** [comment]
Updated the description.

~~But, is this relevant still?~~ Still relevant.
