### ISSUE TITLE
[vscode] Add new chat provider: Typetalk

### ISSUE THREAD

**Issue by is2ei** [arjunattam/vscode-chat#350]
My chat provider is [Typetalk](https://www.typetalk.com).
I'd like to send PR.

**Comment by arjun27** [comment]
Thanks @is2ei. Would love to add this support - feel to share a strawman PR to outline and we can collaborate on it. This doc might help: https://github.com/karigari/vscode-chat/blob/master/docs/PROVIDERS.md
