### ISSUE TITLE
Privacy Policy Request

### ISSUE THREAD

**Issue by ruberVulpes** [arjunattam/vscode-chat#443]
I was wondering if you had a privacy policy that you could supply to our security team for review. At minimum, can you provide a diagram of how the flow would look for a pair of programmers utilizing vs code and slack?  Specifically, please focus on ports and encryption in all phases of the interaction.

**Comment by ericis** [comment]
@arjun27 we can't use this at our company until more information is provided about how the Slack application integration works and legal information like this privacy policy
