### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by voxpelli** [arjunattam/vscode-chat#444]
- Issue Type: `Bug`
- Extension Name: `chat`
- Extension Version: `0.27.1`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.39.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 86,
		"activateCallTime": 8,
		"activateResolvedTime": 7,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "karigari.chat",
				"_lower": "karigari.chat"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'find' of undefined"
		}
	]
}
```

**Comment by arjun27** [comment]
Thanks @voxpelli. Is this happening during activation? Do you have any of slack/discord enabled?

**Comment by voxpelli** [comment]
@arjun27 I don't believe I have either activated. I have no chat-related settings in my settings.json for example, so I think I pretty much use a default setup.

Though: I do have a setup which had this extension added a long long time ago, but I've since removed it and tried readding it many times, never gotten it to work
