### ISSUE TITLE
Feature request - support rocket chat 

### ISSUE THREAD

**Issue by terrylinooo** [arjunattam/vscode-chat#9]
https://rocket.chat/

Is it possible to support rocket chat in the future?

Thanks

**Comment by arjun27** [comment]
Thanks for the request. Yes, definitely possible. Went through their docs and they have the APIs we need[1]. Let me gauge some more interest and then prioritize.

[1] https://rocket.chat/docs/developer-guides/realtime-api/

**Comment by terrylinooo** [comment]
Thank you !

**Comment by artbycrunk** [comment]
hey @arjun27, is there any work started on this chat provider?

**Comment by arjun27** [comment]
Hey @artbycrunk - no, not yet. I have to prioritize multiple workspaces on slack, and MS Teams support before I can commit to this. Would you like to contribute this? I would love to support you along the way

**Comment by artbycrunk** [comment]
sure i can take a look, but be prepared for an array of silly questions :)

**Comment by skarone** [comment]
Hi I would like to know if this will be addressed at some point :)!

**Comment by SDAdham** [comment]
Hello, it's been 3 years for this issue, any news about rocket chat support please?

**Comment by vlebourl** [comment]
> Hello, it's been 3 years for this issue, any news about rocket chat support please?

Hey, would be interested as well, is this planned? 
Cheers
